backend:
  - 'pyproject.toml'
  - 'poetry.lock'
  - 'rasa/**/*'
  - 'tests/**/*'
  - 'data/**/*'
  - 'examples/**/*'
  - 'Makefile'
  - '.github/workflows/continous-integration.yml'
  - '.github/workflows/security-scans.yml'

docker:
  - 'pyproject.toml'
  - 'poetry.lock'
  - 'rasa/**/*'
  - 'docker/**/*'
  - 'Makefile'
