repos:
-   repo: https://github.com/ambv/black
    rev: 21.9b0
    hooks:
    - id: black
-   repo: https://github.com/thlorenz/doctoc
    rev: v2.0.1
    hooks:
    -   id: doctoc
        files: "CONTRIBUTING.md"
