[build-system]
requires = ["poetry-core>=1.0.4"]
build-backend = "poetry.core.masonry.api"

[tool.black]
line-length = 88
target-version = ["py38", "py39", "py310"]
exclude = "(\\.eggs|\\.git|\\.pytest_cache|build|dist)"

[tool.poetry]
name = "rasa"
version = "3.7.1"
description = "Open source machine learning framework for text- and voice-based conversations."
authors = ["Rasa Technologies GmbH <hi@rasa.com>"]
maintainers = ["Tom Bocklisch <tom@rasa.com>"]
homepage = "https://rasa.com"
repository = "https://github.com/rasahq/rasa"
documentation = "https://rasa.com/docs"
classifiers = [
    "Development Status :: 5 - Production/Stable",
    "Intended Audience :: Developers",
    "License :: OSI Approved :: Apache Software License",
    "Topic :: Software Development :: Libraries"
]
keywords = [
    "nlp", "machine-learning", "bot", "conversational-ai", "chatbot", "rasa"
]
readme = "README.md"
license = "Apache-2.0"
include = [
    "LICENSE.txt", "README.md", "rasa/shared/core/training_data/visualization.html", 
    "rasa/cli/default_config.yml", "rasa/shared/importers/*", "rasa/utils/schemas/*", "rasa/keys"
]
[[tool.poetry.source]]
name = "internal repository mirroring psycopg binary for macos"
url = "https://pypi.org/simple/"

[tool.poetry.dependencies]
python = ">=3.10, <3.11"
rasa-sdk = ">=3.6.2"
aiohttp = ">=3.10.2"
boto3 = ">=1.26.136"
requests = ">=2.23"
matplotlib = ">=3.1"
attrs = ">=19.3"
redis = ">=4.5.3"
tqdm = ">=4.31"
networkx = ">=2.4"
"ruamel.yaml" = ">=0.16.5"
pyyaml = ">=6.0"
SQLAlchemy = "^1.4.0"
protobuf = ">=4.23.3"
cloudpickle = ">=1.2"
jsonschema = ">=3.2"
tensorflow_hub = ">=0.16.1"
setuptools = ">=65.5.1"
certifi = ">=2023.7.22"
cryptography = ">=43.0.1"
structlog = ">=23.1.0"
structlog-sentry = ">=2.1.0"
pydantic = { extras = ["dotenv"], version = "^1" }
terminaltables = ">=3.1.0"
tarsafe = ">=0.0.3"
absl-py = ">=0.9"
apscheduler = ">=3.6"
fbmessenger = ">=6.0.0"
pykwalify = ">=1.7"
coloredlogs = ">=10"
twilio = ">=6.26"
webexteamssdk = ">=1.1.1"
mattermostwrapper = ">=2.2"
rocketchat_API = ">=0.6.31"
colorhash = ">=1.0.2"
jsonpickle = ">=1.3"
packaging = "^21"
pytz = ">=2019.1"
colorclass = ">=2.2"
sanic = ">=21.12"
sanic-cors = ">=2.0.0"
sanic-jwt = ">=1.6.0"
sanic-routing = ">=0.7.2"
websockets = ">=10.0"
questionary = ">=1.5.1"
prompt-toolkit = ">=3.0"
python-socketio = ">=4.4,"
python-engineio = ">=4"
pydot = ">=1.4"
sklearn-crfsuite = ">=0.3"
psycopg2-binary = ">=2.8.2"
python-dateutil = ">=2.8"
ujson = ">=1.35"
regex = ">=2020.6"
joblib = ">=0.15.1"
sentry-sdk = ">=0.17.0"
aio-pika = ">=6.7.1"
aiogram = "<2.26"
typing-extensions = ">=4.1.1"
typing-utils = ">=0.1.0"
google-auth = "<3"
CacheControl = ">=0.12.9"
randomname = ">=0.2.1"
pluggy = ">=1.0.0"
slack-sdk = ">=3.19.2"
confluent-kafka = ">=1.9.2"
portalocker = ">=2.7.0"
dnspython = "2.3.0"
wheel = ">=0.38.1"
lockfile = ">=0.12.2"
spacy = { version = ">=3.7.6", markers = "sys_platform == 'darwin' and platform_machine == 'arm64'" }


# TensorFlow-related dependencies for different platforms
tensorflow = { version = "2.14.0", markers = "sys_platform != 'darwin' or platform_machine != 'arm64'" }
tensorflow-intel = { version = "2.14.0", markers = "sys_platform == 'win32'" }
tensorflow-cpu-aws = { version = "2.14.0", markers = "sys_platform == 'linux' and (platform_machine == 'arm64' or platform_machine == 'aarch64')" }
tensorflow-macos = { version = "2.14.0", markers = "sys_platform == 'darwin' and platform_machine == 'arm64'" }
tensorflow-text = { version = "2.14.0", markers = "sys_platform != 'win32' and platform_machine != 'arm64' and platform_machine != 'aarch64'" }
tensorflow-metal = { version = ">=1.1.0", markers = "sys_platform == 'darwin' and platform_machine == 'arm64'", optional = true }

# TensorFlow IO GCS Filesystem with platform-specific markers
tensorflow-io-gcs-filesystem = [
    { version = ">=0.31", markers = "sys_platform == 'win32'" },
    { version = ">=0.32", markers = "sys_platform == 'linux'" },
    { version = ">=0.32", markers = "sys_platform == 'darwin' and platform_machine != 'arm64'" }
]


# Extra packages
transformers = { version = ">=4.13.0", optional = true }
sentencepiece = { version = ">=0.1.99", optional = true }

[tool.poetry.extras]
transformers = ["transformers", "sentencepiece"]
full = ["transformers", "sentencepiece"]
metal = [ "tensorflow-metal",]

# Development dependencies
[tool.poetry.dev-dependencies]
pytest-sanic = { git = "https://github.com/RasaHQ/pytest-sanic", branch = "fix_signal_issue" }

[tool.mypy]
ignore_missing_imports = true
show_error_codes = true
warn_unused_ignores = true
disallow_untyped_calls = true

[tool.ruff]
ignore = ["D100", "D104", "D105", "RUF001", "RUF002"]
line-length = 88
select = ["D", "E", "F", "W", "RUF"]

[tool.ruff.pydocstyle]
convention = "google"

[tool.ruff.per-file-ignores]
"tests/test_telemetry.py" = ["E501"]
"tests/shared/core/test_domain.py" = ["E501"]

[tool.pytest.ini_options]
python_functions = "test_"
filterwarnings = ["ignore::ResourceWarning:ruamel[.*]"]
timeout = 60
asyncio_mode = "auto"


[tool.poetry.dependencies.pymongo]
version = ">=3.8"
extras = [ "tls", "srv",]

[[tool.poetry.dependencies.dask]]
version = "^2022"
python = ">=3.10"

[[tool.poetry.dependencies.numpy]]
version = ">=1.23.5,<2"
python = ">=3.8,<3.11"

[[tool.poetry.dependencies.numpy]]
version = ">=1.23.5,<2"
markers = "sys_platform =='Windows' and platform_python_implementation != 'PyPy'"
python = "3.10"
