receivers:
  otlp:
    protocols:
      grpc:
        endpoint: 0.0.0.0:4317
        tls:
          ca_file: /etc/otelcol-tls/ca.pem
          cert_file: /etc/otelcol-tls/cert.pem
          key_file: /etc/otelcol-tls/cert-key.pem

exporters:
  prometheus:
    endpoint: 0.0.0.0:8889

  debug:

service:
  pipelines:
    traces:
      receivers: [otlp]
      exporters: [debug]
    metrics:
      receivers: [otlp]
      exporters: [prometheus]
