recipe: default.v1
assistant_id: mood_bot
language: en

pipeline:
  - name: LLMCommandGenerator
    llm:
      model_name: gpt-4

policies:
  - name: rasa.core.policies.flow_policy.FlowPolicy
  - name: RulePolicy
