recipe: default.v1
language: en
pipeline:
- name: LLMCommandGenerator
  llm:
    model_name: gpt-4
    request_timeout: 7
    max_tokens: 256

policies:
- name: rasa.core.policies.flow_policy.FlowPolicy
assistant_id: 20231103-211221-milky-crop
