language: en

pipeline:
- name: SpacyNLP
  model: "en_core_web_md"
- name: SpacyTokenizer
- name: SpacyEntityExtractor
- name: SpacyFeaturizer
  pooling: mean
- name: CountVectorsFeaturizer
  analyzer: char_wb
  min_ngram: 1
  max_ngram: 4
- name: DIETClassifier
  epochs: 1
- name: STSFallbackTrainer
  host: "127.0.0.1"
  port: "9502"
  dropout: 0.1
  accumulate_gradient: 1
  patience: 100
  max_epochs: 200
  max_steps: 500
  eval_frequency: 200

policies:
  - name: MappingPolicy