name: MR Test Reusable workflow

on:
  workflow_call:
    inputs:
      username:
        required: true
        type: string
    secrets:
      DD_API_KEY:
        required: true

jobs:
  reusable_workflow_job:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Print
        run: |-
          set -x
          echo ${{ inputs.username }}
          echo ${{ secrets.DD_API_KEY }}
      - name: Checkout dataset
        uses: actions/checkout@v2
        with:
          repository: ${{ secrets.DATASET_REPOSITORY }}
          token: ${{ secrets.ML_TEST_SA_PAT }}
          path: 'dataset'
          ref: ${{ matrix.dataset_branch }}
