name: MR Test Reusable workflow

on:
  workflow_call:
    inputs:
      dataset_branch:
        required: true
        type: string
    secrets:
      DD_API_KEY:
        required: true
      ML_TEST_SA_PAT:
        required: true
      DATASET_REPOSITORY:
        required: true

jobs:
  reusable_workflow_job:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Checkout dataset
        uses: actions/checkout@v2
        with:
          repository: ${{ secrets.DATASET_REPOSITORY }}
          token: ${{ secrets.ML_TEST_SA_PAT }}
          path: 'dataset'
          ref: ${{ input.dataset_branch }}
