name: Backup Rasa repo to S3
on:
  schedule:
    # Run cron job at 7AM Monday to Sunday.
    - cron: "0 7 * * *"
  workflow_dispatch:

permissions:
  id-token: write
  contents: read

jobs:
  backup:
    runs-on: ubuntu-22.04
    steps:
      - name: Checkout repository
        uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683
        with:
          fetch-depth: 0
    
      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@e3dd6a429d7300a6a4c196c26e071d42e0343502 #v3.0.1
        with:
          role-to-assume: ${{ secrets.GIT_BACKUP_ROLE_ARN }}
          aws-region: ${{ secrets.GIT_BACKUP_REGION }}
    
      # Determine the date in the right format for us to tag the image.
      - name: Get current date
        id: date
        run: echo "date=$(date +'%Y%m%d')" >> $GITHUB_OUTPUT
  
      - name: Create Git bundle
        run: git bundle create --progress rasa-${{ steps.date.outputs.date }}.bundle --all

      - name: Verify Git bundle
        run: git bundle verify rasa-${{ steps.date.outputs.date }}.bundle

      - name: Upload bundle to S3
        run: aws s3 cp rasa-${{ steps.date.outputs.date }}.bundle s3://${{ secrets.GIT_BACKUP_BUCKET }}/rasa/